### ISSUE TITLE
integration of cyjShiny

### ISSUE THREAD

**Issue by roStats** [hyu-ub/BayesNetBP#1]
It appears that runBayesNetApp() has not updated with the move of rcytoscape to cyjShiny. Please update functions across ui.R, server.R and global.R 

(there is generally a nice one-to-one, up until lines 368-369 in server.R:
   network <- createCytoscapeJsNetwork(nodeData.2, edgeData.2)
    rcytoscapejs(network$nodes, network$edges, showPanzoom=TRUE, 

your package looks exciting, so I can't wait to try it!!

**Comment by hyu-ub** [comment]
Hi roStats, thank you very much for your comment. I will work on the updates.

**Comment by hyu-ub** [comment]
The Shiny app has been updated with cyjShiny.
