### ISSUE TITLE
ShinyApp does not load the BN

### ISSUE THREAD

**Issue by mahdiprs** [hyu-ub/BayesNetBP#3]
Hi,

Thank you for developing such a great package for Bayesian inference. The interactive ShinyApp is super useful for communicating the model results and live inference. Unfortunately, it does not work properly even with toy BN. The network does not load and only shows a blank box. 

Thanks
M

**Comment by hyu-ub** [comment]
My apologies for the delay in response. The issue should have been fixed now.
